INSERT INTO CATEGORY (DESCRIPTION) VALUES ('American');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Italian');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Mexican');
INSERT INTO CATEGORY (DESCRIPTION) VALUES ('Fast Food');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Clove');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Small');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Medium');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Pint');
INSERT INTO UNIT_OF_MEASURE (DESCRIPTION) VALUES ('Dash');

